version: "3"

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/app/
        # Dependencies between containers
        links:
            - php
        networks:
            - pg-network

    db:
        build:
            context: .
            dockerfile: docker/db/Dockerfile
        ports:
            - "5433:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - pg-network

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/app/
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - pg-network

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pg-admin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        networks:
            - pg-network

networks:
    pg-network:

volumes:
    db-data:
    pgadmin-data:
